service: server

provider:
  name: aws
  runtime: nodejs14.x
  stage: card
  region: us-east-1
  memorySize: 256
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: arn:aws:logs:*:*:*

functions:
  createToken:
    handler: dist/index.handler
    events:
      - http:
          path: token
          method: POST
  getCard:
    handler: dist/index.handler
    events:
      - http:
          path: token/{token}
          method: GET

plugins:
  - serverless-offline
